# Generated by Django 4.1.3 on 2022-11-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('imagen', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200, null=True)),
                ('explicacion', models.TextField(blank=True)),
                ('imagen', models.ImageField(upload_to='media')),
                ('opciones', models.ManyToManyField(to='preguntas.respuestamultiple')),
                ('respuesta_correcta', models.ManyToManyField(blank=True, related_name='correcta', to='preguntas.respuestamultiple')),
            ],
        ),
    ]
