# Generated by Django 4.1.3 on 2022-11-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0002_alter_pregunta_imagen_alter_respuestamultiple_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='contexto',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
