# Generated by Django 4.1.3 on 2022-11-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0003_pregunta_contexto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='contexto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
