# Generated by Django 4.1.3 on 2022-11-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0004_alter_pregunta_contexto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='categoria',
            field=models.CharField(blank=True, choices=[('CN', 'Ciencias'), ('MA', 'Matematicas'), ('LE', 'Lectura'), ('IN', 'Ingles'), ('SC', 'Sociales')], default='CN', max_length=2, null=True),
        ),
    ]
