# Generated by Django 4.1.3 on 2022-11-07 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0007_rename_description_quiz_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='fecha_agregado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='fecha_modificado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
