# Generated by Django 4.1.3 on 2022-11-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0008_alter_quiz_fecha_agregado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='contexto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
