# Generated by Django 4.1.3 on 2022-11-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0009_alter_pregunta_contexto_alter_pregunta_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestamultiple',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
