# Generated by Django 4.1.3 on 2022-11-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0010_alter_respuestamultiple_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='respuestas_tienen_imagen',
            field=models.BooleanField(default=False),
        ),
    ]
