# Generated by Django 4.1.3 on 2022-11-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0011_pregunta_respuestas_tienen_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
