# Generated by Django 4.1.3 on 2022-11-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0012_alter_quiz_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='categoria',
            field=models.CharField(blank=True, choices=[('ciencias', 'ciencias'), ('matematicas', 'matematicas'), ('lectura', 'lectura'), ('ingles', 'ingles'), ('sociales', 'sociales')], default='ciencias', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='categoria',
            field=models.CharField(choices=[('ciencias', 'ciencias'), ('matematicas', 'matematicas'), ('lectura', 'lectura'), ('ingles', 'ingles'), ('sociales', 'sociales')], default='ciencias', max_length=12),
        ),
    ]
